### PR TITLE
Add support for arm64-v8a for Apple Silicon Macs

### PR DESCRIPTION
**Pull request by Jeehut**
Fixes https://github.com/ReactiveCircus/android-emulator-runner/issues/145

### CODE REVIEW

**Review by ychescale9 — APPROVED** [review]
Thanks!

**Comment by christinachimi** [comment]
Any idea when this might release? Trying to decide whether to soldier on with my self-hosted Mac Mini or throw in the towel and take a different approach. This feature would help a ton!

**Comment by ychescale9** [comment]
I'll do a release tomorrow:)

**Comment by ychescale9** [comment]
This has now been released.

**Pull request merged**
