### PR TITLE
Add GHA commands to group logs

### PR DESCRIPTION
**Pull request by michaelkaye**
Suggest reviewing with `diff -w` as the majority of the change is whitespace indentation.

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines

### CODE REVIEW

**Comment by michaelkaye** [comment]
New split looks like this:

Summary

**Comment by ychescale9** [comment]
Looks great! Can you `run npm run build` and check in the generated js files?

**Comment by michaelkaye** [comment]
Er, maybe; I don't have a npm setup locally I can use for this; I'd have to knock something up with docker or similar (which is why i like the draft PR as a way to lint and compile using the GHA :)

I'll see if i can sort it out soon, otherwise feel free to take the change and push it live.

**Comment by ychescale9** [comment]
No worries I can take over. Thanks again for the great contribution!

**Pull request merged**
